const countryCodes = [
    { id: 'ad', label: 'Andorra', value: '+376', flag: '🇦🇩' },
    { id: 'ae', label: 'United Arab Emirates', value: '+971', flag: '🇦🇪' },
    { id: 'af', label: 'Afghanistan', value: '+93', flag: '🇦🇫' },
    { id: 'ag', label: 'Antigua and Barbuda', value: '+1', flag: '🇦🇬' },
    { id: 'al', label: 'Albania', value: '+355', flag: '🇦🇱' },
    { id: 'am', label: 'Armenia', value: '+374', flag: '🇦🇲' },
    { id: 'ao', label: 'Angola', value: '+244', flag: '🇦🇴' },
    { id: 'ar', label: 'Argentina', value: '+54', flag: '🇦🇷' },
    { id: 'as', label: 'American Samoa', value: '+1', flag: '🇦🇸' },
    { id: 'at', label: 'Austria', value: '+43', flag: '🇦🇹' },
    { id: 'au', label: 'Australia', value: '+61', flag: '🇦🇺' },
    { id: 'aw', label: 'Aruba', value: '+297', flag: '🇦🇼' },
    { id: 'ba', label: 'Bosnia and Herzegovina', value: '+387', flag: '🇧🇦' },
    { id: 'bb', label: 'Barbados', value: '+1', flag: '🇧🇧' },
    { id: 'bd', label: 'Bangladesh', value: '+880', flag: '🇧🇩' },
    { id: 'be', label: 'Belgium', value: '+32', flag: '🇧🇪' },
    { id: 'bf', label: 'Burkina Faso', value: '+226', flag: '🇧🇫' },
    { id: 'bg', label: 'Bulgaria', value: '+359', flag: '🇧🇬' },
    { id: 'bj', label: 'Benin', value: '+229', flag: '🇧🇯' },
    { id: 'bm', label: 'Bermuda', value: '+1', flag: '🇧🇲' },
    { id: 'bn', label: 'Brunei Darussalam', value: '+673', flag: '🇧🇳' },
    { id: 'bo', label: 'Bolivia', value: '+591', flag: '🇧🇴' },
    { id: 'br', label: 'Brazil', value: '+55', flag: '🇧🇷' },
    { id: 'bs', label: 'Bahamas', value: '+1', flag: '🇧🇸' },
    { id: 'bt', label: 'Bhutan', value: '+975', flag: '🇧🇹' },
    { id: 'bw', label: 'Botswana', value: '+267', flag: '🇧🇼' },
    { id: 'by', label: 'Belarus', value: '+375', flag: '🇧🇾' },
    { id: 'bz', label: 'Belize', value: '+501', flag: '🇧🇿' },
    { id: 'ca', label: 'Canada', value: '+1', flag: '🇨🇦' },
    { id: 'cd', label: 'Congo, (Kinshasa)', value: '+243', flag: '🇨🇩' },
    { id: 'cf', label: 'Central African Republic', value: '+236', flag: '🇨🇫' },
    { id: 'cg', label: 'Congo (Brazzaville)', value: '+242', flag: '🇨🇬' },
    { id: 'ch', label: 'Switzerland', value: '+41', flag: '🇨🇭' },
    { id: 'ci', label: 'Côte d\'Ivoire', value: '+225', flag: '🇨🇮' },
    { id: 'ck', label: 'Cook Islands', value: '+682', flag: '🇨🇰' },
    { id: 'cl', label: 'Chile', value: '+56', flag: '🇨🇱' },
    { id: 'cm', label: 'Cameroon', value: '+237', flag: '🇨🇲' },
    { id: 'co', label: 'Colombia', value: '+57', flag: '🇨🇴' },
    { id: 'cr', label: 'Costa Rica', value: '+506', flag: '🇨🇷' },
    { id: 'cv', label: 'Cape Verde', value: '+238', flag: '🇨🇻' },
    { id: 'cw', label: 'Curaçao', value: '+599', flag: '🇨🇼' },
    { id: 'cy', label: 'Cyprus', value: '+357', flag: '🇨🇾' },
    { id: 'cz', label: 'Czech Republic', value: '+420', flag: '🇨🇿' },
    { id: 'de', label: 'Germany', value: '+49', flag: '🇩🇪' },
    { id: 'dj', label: 'Djibouti', value: '+253', flag: '🇩🇯' },
    { id: 'dk', label: 'Denmark', value: '+45', flag: '🇩🇰' },
    { id: 'dm', label: 'Dominica', value: '+1', flag: '🇩🇲' },
    { id: 'do', label: 'Dominican Republic', value: '+1', flag: '🇩🇴' },
    { id: 'dz', label: 'Algeria', value: '+213', flag: '🇩🇿' },
    { id: 'ec', label: 'Ecuador', value: '+593', flag: '🇪🇨' },
    { id: 'eg', label: 'Egypt', value: '+20', flag: '🇪🇬' },
    { id: 'es', label: 'Spain', value: '+34', flag: '🇪🇸' },
    { id: 'et', label: 'Ethiopia', value: '+251', flag: '🇪🇹' },
    { id: 'fi', label: 'Finland', value: '+358', flag: '🇫🇮' },
    { id: 'fj', label: 'Fiji', value: '+679', flag: '🇫🇯' },
    { id: 'fk', label: 'Falkland Islands (Malvinas)', value: '+500', flag: '🇫🇰' },
    { id: 'fm', label: 'Micronesia, Federated States of', value: '+691', flag: '🇫🇲' },
    { id: 'fo', label: 'Faroe Islands', value: '+298', flag: '🇫🇴' },
    { id: 'fr', label: 'France', value: '+33', flag: '🇫🇷' },
    { id: 'ga', label: 'Gabon', value: '+241', flag: '🇬🇦' },
    { id: 'gb', label: 'United Kingdom', value: '+44', flag: '🇬🇧' },
    { id: 'gd', label: 'Grenada', value: '+1', flag: '🇬🇩' },
    { id: 'ge', label: 'Georgia', value: '+995', flag: '🇬🇪' },
    { id: 'gf', label: 'French Guiana', value: '+594', flag: '🇬🇫' },
    { id: 'gg', label: 'Guernsey', value: '+44', flag: '🇬🇬' },
    { id: 'gh', label: 'Ghana', value: '+233', flag: '🇬🇭' },
    { id: 'gi', label: 'Gibraltar', value: '+350', flag: '🇬🇮' },
    { id: 'gl', label: 'Greenland', value: '+299', flag: '🇬🇱' },
    { id: 'gm', label: 'Gambia', value: '+220', flag: '🇬🇲' },
    { id: 'gp', label: 'Guadeloupe', value: '+590', flag: '🇬🇵' },
    { id: 'gq', label: 'Equatorial Guinea', value: '+240', flag: '🇬🇶' },
    { id: 'gr', label: 'Greece', value: '+30', flag: '🇬🇷' },
    { id: 'gt', label: 'Guatemala', value: '+502', flag: '🇬🇹' },
    { id: 'gy', label: 'Guyana', value: '+592', flag: '🇬🇾' },
    { id: 'hk', label: 'Hong Kong, SAR China', value: '+852', flag: '🇭🇰' },
    { id: 'hn', label: 'Honduras', value: '+504', flag: '🇭🇳' },
    { id: 'hr', label: 'Croatia', value: '+385', flag: '🇭🇷' },
    { id: 'ht', label: 'Haiti', value: '+509', flag: '🇭🇹' },
    { id: 'hu', label: 'Hungary', value: '+36', flag: '🇭🇺' },
    { id: 'id', label: 'Indonesia', value: '+62', flag: '🇮🇩' },
    { id: 'ie', label: 'Ireland', value: '+353', flag: '🇮🇪' },
    { id: 'il', label: 'Israel', value: '+972', flag: '🇮🇱' },
    { id: 'im', label: 'Isle of Man', value: '+44', flag: '🇮🇲' },
    { id: 'in', label: 'India', value: '+91', flag: '🇮🇳' },
    { id: 'iq', label: 'Iraq', value: '+964', flag: '🇮🇶' },
    { id: 'it', label: 'Italy', value: '+39', flag: '🇮🇹' },
    { id: 'je', label: 'Jersey', value: '+44', flag: '🇯🇪' },
    { id: 'jm', label: 'Jamaica', value: '+1', flag: '🇯🇲' },
    { id: 'jo', label: 'Jordan', value: '+962', flag: '🇯🇴' },
    { id: 'jp', label: 'Japan', value: '+81', flag: '🇯🇵' },
    { id: 'ke', label: 'Kenya', value: '+254', flag: '🇰🇪' },
    { id: 'kg', label: 'Kyrgyzstan', value: '+996', flag: '🇰🇬' },
    { id: 'kh', label: 'Cambodia', value: '+855', flag: '🇰🇭' },
    { id: 'km', label: 'Comoros', value: '+269', flag: '🇰🇲' },
    { id: 'kn', label: 'Saint Kitts and Nevis', value: '+1', flag: '🇰🇳' },
    { id: 'kr', label: 'Korea (South)', value: '+82', flag: '🇰🇷' },
    { id: 'kw', label: 'Kuwait', value: '+965', flag: '🇰🇼' },
    { id: 'ky', label: 'Cayman Islands', value: '+1', flag: '🇰🇾' },
    { id: 'kz', label: 'Kazakhstan', value: '+7', flag: '🇰🇿' },
    { id: 'la', label: 'Lao PDR', value: '+856', flag: '🇱🇦' },
    { id: 'lb', label: 'Lebanon', value: '+961', flag: '🇱🇧' },
    { id: 'lc', label: 'Saint Lucia', value: '+1', flag: '🇱🇨' },
    { id: 'li', label: 'Liechtenstein', value: '+423', flag: '🇱🇮' },
    { id: 'lk', label: 'Sri Lanka', value: '+94', flag: '🇱🇰' },
    { id: 'ls', label: 'Lesotho', value: '+266', flag: '🇱🇸' },
    { id: 'lt', label: 'Lithuania', value: '+370', flag: '🇱🇹' },
    { id: 'lu', label: 'Luxembourg', value: '+352', flag: '🇱🇺' },
    { id: 'lv', label: 'Latvia', value: '+371', flag: '🇱🇻' },
    { id: 'ly', label: 'Libya', value: '+218', flag: '🇱🇾' },
    { id: 'ma', label: 'Morocco', value: '+212', flag: '🇲🇦' },
    { id: 'md', label: 'Moldova', value: '+373', flag: '🇲🇩' },
    { id: 'me', label: 'Montenegro', value: '+382', flag: '🇲🇪' },
    { id: 'mf', label: 'Saint-Martin (French part)', value: '+590', flag: '🇲🇫' },
    { id: 'mg', label: 'Madagascar', value: '+261', flag: '🇲🇬' },
    { id: 'mk', label: 'Macedonia, Republic of', value: '+389', flag: '🇲🇰' },
    { id: 'mm', label: 'Myanmar', value: '+95', flag: '🇲🇲' },
    { id: 'mn', label: 'Mongolia', value: '+976', flag: '🇲🇳' },
    { id: 'mo', label: 'Macao, SAR China', value: '+853', flag: '🇲🇴' },
    { id: 'ms', label: 'Montserrat', value: '+1', flag: '🇲🇸' },
    { id: 'mt', label: 'Malta', value: '+356', flag: '🇲🇹' },
    { id: 'mu', label: 'Mauritius', value: '+230', flag: '🇲🇺' },
    { id: 'mw', label: 'Malawi', value: '+265', flag: '🇲🇼' },
    { id: 'mx', label: 'Mexico', value: '+52', flag: '🇲🇽' },
    { id: 'my', label: 'Malaysia', value: '+60', flag: '🇲🇾' },
    { id: 'mz', label: 'Mozambique', value: '+258', flag: '🇲🇿' },
    { id: 'na', label: 'Namibia', value: '+264', flag: '🇳🇦' },
    { id: 'nc', label: 'New Caledonia', value: '+687', flag: '🇳🇨' },
    { id: 'ne', label: 'Niger', value: '+227', flag: '🇳🇪' },
    { id: 'nf', label: 'Norfolk Island', value: '+672', flag: '🇳🇫' },
    { id: 'ng', label: 'Nigeria', value: '+234', flag: '🇳🇬' },
    { id: 'ni', label: 'Nicaragua', value: '+505', flag: '🇳🇮' },
    { id: 'nl', label: 'Netherlands', value: '+31', flag: '🇳🇱' },
    { id: 'no', label: 'Norway', value: '+47', flag: '🇳🇴' },
    { id: 'np', label: 'Nepal', value: '+977', flag: '🇳🇵' },
    { id: 'nz', label: 'New Zealand', value: '+64', flag: '🇳🇿' },
    { id: 'om', label: 'Oman', value: '+968', flag: '🇴🇲' },
    { id: 'pa', label: 'Panama', value: '+507', flag: '🇵🇦' },
    { id: 'pe', label: 'Peru', value: '+51', flag: '🇵🇪' },
    { id: 'pg', label: 'Papua New Guinea', value: '+675', flag: '🇵🇬' },
    { id: 'ph', label: 'Philippines', value: '+63', flag: '🇵🇭' },
    { id: 'pk', label: 'Pakistan', value: '+92', flag: '🇵🇰' },
    { id: 'pl', label: 'Poland', value: '+48', flag: '🇵🇱' },
    { id: 'pm', label: 'Saint Pierre and Miquelon', value: '+508', flag: '🇵🇲' },
    { id: 'pr', label: 'Puerto Rico', value: '+1', flag: '🇵🇷' },
    { id: 'ps', label: 'Palestinian Territory', value: '+970', flag: '🇵🇸' },
    { id: 'pt', label: 'Portugal', value: '+351', flag: '🇵🇹' },
    { id: 'py', label: 'Paraguay', value: '+595', flag: '🇵🇾' },
    { id: 'qa', label: 'Qatar', value: '+974', flag: '🇶🇦' },
    { id: 're', label: 'Réunion', value: '+262', flag: '🇷🇪' },
    { id: 'ro', label: 'Romania', value: '+40', flag: '🇷🇴' },
    { id: 'rs', label: 'Serbia', value: '+381', flag: '🇷🇸' },
    { id: 'ru', label: 'Russian Federation', value: '+7', flag: '🇷🇺' },
    { id: 'rw', label: 'Rwanda', value: '+250', flag: '🇷🇼' },
    { id: 'sa', label: 'Saudi Arabia', value: '+966', flag: '🇸🇦' },
    { id: 'sc', label: 'Seychelles', value: '+248', flag: '🇸🇨' },
    { id: 'sd', label: 'Sudan', value: '+249', flag: '🇸🇩' },
    { id: 'se', label: 'Sweden', value: '+46', flag: '🇸🇪' },
    { id: 'sg', label: 'Singapore', value: '+65', flag: '🇸🇬' },
    { id: 'sh', label: 'Saint Helena', value: '+290', flag: '🇸🇭' },
    { id: 'si', label: 'Slovenia', value: '+386', flag: '🇸🇮' },
    { id: 'sk', label: 'Slovakia', value: '+421', flag: '🇸🇰' },
    { id: 'sl', label: 'Sierra Leone', value: '+232', flag: '🇸🇱' },
    { id: 'sn', label: 'Senegal', value: '+221', flag: '🇸🇳' },
    { id: 'sr', label: 'Suriname', value: '+597', flag: '🇸🇷' },
    { id: 'st', label: 'Sao Tome and Principe', value: '+239', flag: '🇸🇹' },
    { id: 'sv', label: 'El Salvador', value: '+503', flag: '🇸🇻' },
    { id: 'sy', label: 'Syrian Arab Republic (Syria)', value: '+963', flag: '🇸🇾' },
    { id: 'sz', label: 'Swaziland', value: '+268', flag: '🇸🇿' },
    { id: 'tc', label: 'Turks and Caicos Islands', value: '+1', flag: '🇹🇨' },
    { id: 'tg', label: 'Togo', value: '+228', flag: '🇹🇬' },
    { id: 'th', label: 'Thailand', value: '+66', flag: '🇹🇭' },
    { id: 'tl', label: 'Timor-Leste', value: '+670', flag: '🇹🇱' },
    { id: 'tm', label: 'Turkmenistan', value: '+993', flag: '🇹🇲' },
    { id: 'to', label: 'Tonga', value: '+676', flag: '🇹🇴' },
    { id: 'tr', label: 'Turkey', value: '+90', flag: '🇹🇷' },
    { id: 'tt', label: 'Trinidad and Tobago', value: '+1', flag: '🇹🇹' },
    { id: 'tw', label: 'Taiwan, Republic of China', value: '+886', flag: '🇹🇼' },
    { id: 'tz', label: 'Tanzania, United Republic of', value: '+255', flag: '🇹🇿' },
    { id: 'ua', label: 'Ukraine', value: '+380', flag: '🇺🇦' },
    { id: 'ug', label: 'Uganda', value: '+256', flag: '🇺🇬' },
    { id: 'us', label: 'United States of America', value: '+1', flag: '🇺🇸' },
    { id: 'uy', label: 'Uruguay', value: '+598', flag: '🇺🇾' },
    { id: 'uz', label: 'Uzbekistan', value: '+998', flag: '🇺🇿' },
    { id: 'vc', label: 'Saint Vincent and Grenadines', value: '+1', flag: '🇻🇨' },
    { id: 've', label: 'Venezuela (Bolivarian Republic)', value: '+58', flag: '🇻🇪' },
    { id: 'vg', label: 'British Virgin Islands', value: '+1', flag: '🇻🇬' },
    { id: 'vi', label: 'Virgin Islands, US', value: '+1', flag: '🇻🇮' },
    { id: 'vn', label: 'Viet Nam', value: '+84', flag: '🇻🇳' },
    { id: 'ws', label: 'Samoa', value: '+685', flag: '🇼🇸' },
    { id: 'ye', label: 'Yemen', value: '+967', flag: '🇾🇪' },
    { id: 'yt', label: 'Mayotte', value: '+262', flag: '🇾🇹' },
    { id: 'za', label: 'South Africa', value: '+27', flag: '🇿🇦' },
    { id: 'zm', label: 'Zambia', value: '+260', flag: '🇿🇲' },
    { id: 'zw', label: 'Zimbabwe', value: '+263', flag: '🇿🇼' }
  ];
  
export default countryCodes;